# Generated by Django 4.1.7 on 2023-03-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_newtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=100)),
                ('Length', models.CharField(max_length=10)),
                ('Height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('110', 'SN1-110'), ('160', 'SN1-160'), ('200', 'SN1-200')], max_length=10)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
